import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'bin/install.ts',
    'bin/update.ts',
    'bin/ez-tools.ts',
    'scripts/build-hooks.ts',
    'scripts/fix-qwen-installation.ts',
    'scripts/fix-test-imports.ts',
    'hooks/ez-check-update.ts',
    'hooks/ez-context-monitor.ts',
    'hooks/ez-statusline.ts',
    'bin/lib/index.ts',
    'bin/lib/core.ts',
    'bin/lib/state.ts',
    'bin/lib/phase.ts',
    'bin/lib/milestone.ts',
    'bin/lib/roadmap.ts',
    'bin/lib/verify.ts',
    'bin/lib/commands.ts',
    'bin/lib/init.ts',
    'bin/lib/frontmatter.ts',
    'bin/lib/logger.ts',
    'bin/lib/file-lock.ts',
    'bin/lib/cost-tracker.ts',
    'bin/lib/cost-alerts.ts',
    'bin/lib/health-check.ts',
    'bin/lib/session-manager.ts',
    'bin/lib/git-utils.ts',
    'bin/lib/git-workflow-engine.ts',
    'bin/lib/release-validator.ts',
    'bin/lib/tier-manager.ts',
    'bin/lib/context-manager.ts',
    'bin/lib/context-cache.ts',
    'bin/lib/archetype-detector.ts',
    'bin/lib/business-flow-mapper.ts',
    'bin/lib/codebase-analyzer.ts',
    'bin/lib/constraint-extractor.ts',
    'bin/lib/dependency-graph.ts',
    'bin/lib/framework-detector.ts',
    'bin/lib/project-reporter.ts',
    'bin/lib/stack-detector.ts',
    'bin/lib/tech-debt-analyzer.ts',
    'bin/lib/quality-gate.ts',
    'bin/lib/guards/context-budget-guard.ts',
    'bin/lib/guards/hallucination-guard.ts',
    'bin/lib/security-fixes.ts',
    'bin/lib/dispatcher.ts',
    'bin/lib/content-scanner.ts',
    'bin/lib/file-access.ts',
    'bin/lib/planning-write.ts',
    'bin/lib/quality-detector.ts',
    'bin/lib/rca-engine.ts',
    'bin/lib/recovery-manager.ts',
    'bin/lib/revision-loop.ts',
    'bin/lib/skill-resolver.ts',
    'bin/lib/skill-validator.ts',
    'bin/lib/task-formatter.ts',
    'bin/lib/temp-file.ts',
    'bin/lib/timeout-exec.ts',
    'bin/lib/tradeoff-analyzer.ts',
    'bin/lib/url-fetch.ts',
    'bin/lib/learning-tracker.ts',
    'bin/lib/gemini-config.ts',
    'bin/lib/circuit-breaker.ts',
    'bin/lib/adapters/index.ts',
    // Analytics
    'bin/lib/analytics/analytics-collector.ts',
    'bin/lib/analytics/analytics-reporter.ts',
    'bin/lib/analytics/cohort-analyzer.ts',
    'bin/lib/analytics/funnel-analyzer.ts',
    'bin/lib/analytics/nps-tracker.ts',
    // Deploy
    'bin/lib/deploy/deploy-runner.ts',
    'bin/lib/deploy/deploy-status.ts',
    'bin/lib/deploy/deploy-health-check.ts',
    'bin/lib/deploy/deploy-pre-flight.ts',
    'bin/lib/deploy/deploy-rollback.ts',
    'bin/lib/deploy/deploy-env-manager.ts',
    'bin/lib/deploy/deploy-audit-log.ts',
    'bin/lib/deploy/deploy-detector.ts',
    // Finops
    'bin/lib/finops/finops-analyzer.ts',
    'bin/lib/finops/cost-reporter.ts',
    'bin/lib/finops/budget-enforcer.ts',
    'bin/lib/finops/spot-manager.ts',
    // Perf
    'bin/lib/perf/api-monitor.ts',
    'bin/lib/perf/db-optimizer.ts',
    'bin/lib/perf/frontend-performance.ts',
    'bin/lib/perf/perf-analyzer.ts',
    'bin/lib/perf/perf-cli.ts',
    'bin/lib/perf/perf-reporter.ts',
    'bin/lib/perf/regression-detector.ts',
    // Additional
    'bin/lib/code-complexity-analyzer.ts'
  ],
  format: ['esm'],
  outDir: 'dist',
  clean: true,
  dts: false,
  sourcemap: 'inline',
  target: 'node18',
  treeshake: false,
  splitting: false,  // Disable splitting for simpler imports
  platform: 'node',
  external: ['@vue/compiler-sfc'],
  ignoreWatch: ['**/*.cjs', '**/*.js', '**/*.test.ts', '**/*.spec.ts']
});
